### ISSUE TITLE
Anyone could help review the Arch Migrator PRs that are created to build osx-arm64 packages ?

### ISSUE THREAD

**Issue by ivaquero** [conda-forge/metaphone-feedstock#13]
Hi @xhochy, could you please help to merge the Arch Migrator PRs? So that I can install the osx-arm64 build of this package.

**Comment by hmaarrfk** [comment]
On pypi, it seems that the source package is distributed, and the source seems to only contain python files.

To make this noarch, see:

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#architecture-independent-packages

and you would need to define a lower limit on python
```
    - python
# To
    - python  >=3.7
```

Copied over from https://github.com/conda-forge/metaphone-feedstock/pull/12#issuecomment-1236155192

**Comment by ivaquero** [comment]
@hmaarrfk Thank you so much for the review. I will give it a try.

**Comment by ivaquero** [comment]
> On pypi, it seems that the source package is distributed, and the source seems to only contain python files.
> 
> To make this noarch, see:
> 
> https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#architecture-independent-packages
> 
> and you would need to define a lower limit on python
> 
> ```
>     - python
> # To
>     - python  >=3.7
> ```
> 
> Copied over from [#12 (comment)](https://github.com/conda-forge/metaphone-feedstock/pull/12#issuecomment-1236155192)

I just found that the [source repo](https://github.com/oubiwann/metaphone) contains c++ codes, so this cannot be treated as a pure python package. This may be the reason why noarch build failed.

**Comment by hmaarrfk** [comment]
In the current state of the package, no compiler is used or installed at build time on Linux. So there is virtually no chance that any C code is being included on conda forge.

That code may have been added as a backup, or reference

**Comment by ivaquero** [comment]
Thank you for the explanation. I will handle this.

**Comment by ivaquero** [comment]
> In the current state of the package, no compiler is used or installed at build time on Linux. So there is virtually no chance that any C code is being included on conda forge.
> 
> That code may have been added as a backup, or reference

Please review the new PR when you are free. Thanks again for your educational suggestions!
